### ISSUE TITLE
See if adding receiver list to sender list is easy at this time

### ISSUE THREAD

**Issue by Louise-Seamster** [ui-libraries/flint#13]
note: issue of lots of false positives from To: and also cutting at multiple people

Also (we didn't talk about this in the meeting today, just thought of it)--what about the cc: line too?

this will be used to create a list of names that Elliot can start on creating classifications for, primarily organizations at this time.

**Comment by hzadeh17** [comment]
[Here](https://github.com/ui-libraries/flint/blob/master/standardizingrecievermetadata_v1.ipynb) is my first try getting the To:'s and Cc:'s...it seems to work pretty well. I (or Elliot) will have have to go through by hand and see what it isn't catching...

next, I will work to try and keep the organizations attached to the names!

one thing to think about: there is no way that I can think of to systematically ascertain the receiver of any email with an "On..." heading because they aren't anywhere in the metadata...

**Comment by hzadeh17** [comment]
fyi: [her](https://github.com/ui-libraries/flint/blob/master/header_metadata/receivers/standardizingrecievermetadata_v3(1).ipynb)e is the most updated receiver code. includes a list of email addresses that are not attached to a name, fixes little name errors (e.g. Waurfel), and spits out names with frequencies!
