### ISSUE TITLE
create a sample of text to run experiments on

### ISSUE THREAD

**Issue by Louise-Seamster** [ui-libraries/flint#4]
Use the file-names.txt file to select a continuous 200-300 page sample of text files (we'll use DEQ 14 because we've been using it), and copy and paste that list of names into a list on a python notebook. then append the rest of the URL pathname to each item on the list so there's a list of urls you can run loops on for tests. This should be the same section of files you use to create the email-break analyses by hand, so you can both run experiments and look systematically at the same data chunk.

https://github.com/ui-libraries/flint/blob/master/filenames.txt

**Comment by Louise-Seamster** [comment]
read this first: https://github.com/ui-libraries/flint/blob/master/templates/sample_text_from_filelist.ipynb

**Comment by akrinaldi** [comment]
I've pushed a large sample set test file with a working notebook to regex-test-rin, should go through soon. So far, results look promising.

**Comment by hzadeh17** [comment]
Since automation is key, I came up with a [simple code](https://github.com/ui-libraries/flint/blob/master/gettingdeq14filenames.ipynb) to extract only the deq14's from a subset of filenames and open using [Matthew's code](https://github.com/ui-libraries/flint/blob/master/templates/sample_text_from_filelist.ipynb). 
The only problem here is that you still have to go to each bates number in the Google Drive to look at the pdf email (I assume this is what is meant by doing an analysis 'by hand'? but correct me if I'm wrong) and compare to the raw text, which is time-consuming but doable.

**Comment by Louise-Seamster** [comment]
Cool!
I think you can work only within the text files for this question since we’re only interested in the text file formatting, but it may mean splitting them line by line.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
